version: "3.8"
services:
  front:
    build:
      context: ./auth-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
    volumes:
      - "./auth-front:/app"
    depends_on:
      - back

  back:
    build:
      context: ./auth-back
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - "./auth-back:/app"
    environment:
      REFRESH_TOKEN_SECRET: 9ae90761-92eb-4d39-90f4-6c862c19394a
      ACCESS_TOKEN_SECRET: 7438940c-8b4d-47ec-8e0a-9b1f427e25e2
      POSTGRES_DB_URI: postgres://postgres:postgres@db:5432/authdb
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: authdb
    volumes:
      - vidly:/var/lib/postgresql/data

volumes:
  vidly:
